/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import classes.Disciplina;
import javax.swing.JOptionPane;

/**
 *
 * @author aluno
 */
public class TelaCadastro extends javax.swing.JDialog {
    
    private int indice = -1;

    public int getIndice() {
        return indice;
    }

    public void setIndice(int indice) {
        this.indice = indice;
        
        Disciplina d = DisciplinaTADS.listaD.get(indice);
        
        jtxtNome.setText(d.getNome());
        jtxtProfessor.setText(d.getProfessor());
        jtxtHoras.setText(Integer.toString(d.getHoras()));
        
        switch (d.getSemestre()) {
            case 1 -> jrb1s.setSelected(true);
            case 2 -> jrb2s.setSelected(true);
            case 3 -> jrb3s.setSelected(true);
            case 4 -> jrb4s.setSelected(true);
            case 5 -> jrb5s.setSelected(true);
            case 6 -> jrb6s.setSelected(true);
            default -> throw new AssertionError();
        }
    }
    /**
     * Creates new form Cadastro
     */
    public TelaCadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jlblNome = new javax.swing.JLabel();
        jtxtNome = new javax.swing.JTextField();
        jlblProfessor = new javax.swing.JLabel();
        jtxtProfessor = new javax.swing.JTextField();
        jlblHoras = new javax.swing.JLabel();
        jtxtHoras = new javax.swing.JTextField();
        jrb1s = new javax.swing.JRadioButton();
        jrb2s = new javax.swing.JRadioButton();
        jrb3s = new javax.swing.JRadioButton();
        jrb4s = new javax.swing.JRadioButton();
        jrb5s = new javax.swing.JRadioButton();
        jrb6s = new javax.swing.JRadioButton();
        jbtnSalvar = new javax.swing.JButton();
        jbtnSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Disciplinas");

        jlblNome.setText("Nome:");

        jtxtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtNomeActionPerformed(evt);
            }
        });

        jlblProfessor.setText("Professor:");

        jlblHoras.setText("Horas:");

        buttonGroup1.add(jrb1s);
        jrb1s.setText("1° Semestre");

        buttonGroup1.add(jrb2s);
        jrb2s.setText("2° Semestre");

        buttonGroup1.add(jrb3s);
        jrb3s.setText("3° Semestre");

        buttonGroup1.add(jrb4s);
        jrb4s.setText("4° Semestre");

        buttonGroup1.add(jrb5s);
        jrb5s.setText("5° Semestre");

        buttonGroup1.add(jrb6s);
        jrb6s.setText("6° Semestre");

        jbtnSalvar.setText("Salvar");
        jbtnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSalvarActionPerformed(evt);
            }
        });

        jbtnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/sair.png"))); // NOI18N
        jbtnSair.setText("Sair");
        jbtnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jbtnSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jbtnSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtHoras)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlblNome, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlblProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlblHoras, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jrb2s, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jrb3s, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jrb1s, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jrb6s, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jrb5s, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jrb4s, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 137, Short.MAX_VALUE))
                    .addComponent(jtxtProfessor)
                    .addComponent(jtxtNome))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jlblNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlblProfessor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxtProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlblHoras)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxtHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrb1s)
                    .addComponent(jrb4s))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrb2s)
                    .addComponent(jrb5s))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrb3s)
                    .addComponent(jrb6s))
                .addGap(28, 28, 28)
                .addComponent(jbtnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jbtnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtNomeActionPerformed

    private void jbtnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSalvarActionPerformed
        //CONVERTER O CAMPO HORAS
        int horas = 0;
        try{
            horas = Integer.valueOf(jtxtHoras.getText());
            
        }catch(Exception e){
            e.printStackTrace();
        }
        
        //RADIOBUTTON PARA PEGAR O SEMESTRE
        int semestre = 0;
        if(jrb1s.isSelected()){
            semestre = 1;
        }else if(jrb2s.isSelected()){
            semestre = 2;
        }else if(jrb3s.isSelected()){
            semestre = 3;
        }else if(jrb4s.isSelected()){
            semestre = 4;
        }else if(jrb5s.isSelected()){
            semestre = 5;
        }else if(jrb6s.isSelected()){
            semestre = 6;
        }
        
        //TESTANDO OS CAMPOS
        if(jtxtNome.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Preencha o Campo Nome!");
            //REQUESTFOCUS JOGA O CURSOR PARA DENTRO DO CAMPO NOME
            jtxtNome.requestFocus();
        }else if(jtxtProfessor.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Preencha o Campo Professor!");
            //REQUESTFOCUS JOGA O CURSOR PARA DENTRO DO CAMPO PROFESSOR
            jtxtProfessor.requestFocus();
        }else if(horas <= 0){
            JOptionPane.showMessageDialog(null, "Preencha o Campo Horas Com Um Valor Válido!");
            //REQUESTFOCUS JOGA O CURSOR PARA DENTRO DO CAMPO HORAS
            jtxtHoras.requestFocus();
        }else if(semestre == 0){
            JOptionPane.showMessageDialog(null, "Escolha o Semestre!");
            //REQUESTFOCUS JOGA O CURSOR PARA DENTRO DO CAMPO SEMESTRE
            jrb1s.requestFocus();
        }else{
            Disciplina d = new Disciplina(jtxtNome.getText(), jtxtProfessor.getText(), horas, semestre);
            if(indice == -1){
                DisciplinaTADS.listaD.add(d);
            }else{
                DisciplinaTADS.listaD.alterar(d, indice);
                dispose();
            }
        }
    }//GEN-LAST:event_jbtnSalvarActionPerformed

    private void jbtnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSairActionPerformed
        dispose();
    }//GEN-LAST:event_jbtnSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jbtnSair;
    private javax.swing.JButton jbtnSalvar;
    private javax.swing.JLabel jlblHoras;
    private javax.swing.JLabel jlblNome;
    private javax.swing.JLabel jlblProfessor;
    private javax.swing.JRadioButton jrb1s;
    private javax.swing.JRadioButton jrb2s;
    private javax.swing.JRadioButton jrb3s;
    private javax.swing.JRadioButton jrb4s;
    private javax.swing.JRadioButton jrb5s;
    private javax.swing.JRadioButton jrb6s;
    private javax.swing.JTextField jtxtHoras;
    private javax.swing.JTextField jtxtNome;
    private javax.swing.JTextField jtxtProfessor;
    // End of variables declaration//GEN-END:variables
}
