/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import classes.SemestreLetivo;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author vinic
 */
public class TelaCadastroSemestre extends javax.swing.JFrame {
    private int indice = -1;

    public int getIndice() {
        return indice;
    }

    public void setIndice(int indice) {
        this.indice = indice;
        
        SemestreLetivo d = DisciplinaTADS.listaSL.get(indice);
        String ano = d.getAno() + "";
        jftxtAno.setText(ano);
        jftxtDataInicial.setText(new SimpleDateFormat("dd/MM/yyyy").format(d.getDataInicio()));
        jftxtDataFinal.setText(new SimpleDateFormat("dd/MM/yyyy").format(d.getDataFim()));
        
        switch (d.getSemestre()) {
            case 1 -> jcbSemestre.setSelectedIndex(1);
            case 2 -> jcbSemestre.setSelectedIndex(2);
            default -> throw new AssertionError();
        }
    }
    /**
     * Creates new form TelaCadastroSemestre
     */
    public TelaCadastroSemestre() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jftxtAno = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        jcbSemestre = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jftxtDataInicial = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jftxtDataFinal = new javax.swing.JFormattedTextField();
        jbtnFechar = new javax.swing.JButton();
        jbtnSalvar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro Semestres Letivos");

        jLabel1.setText("Ano:");

        jftxtAno.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy"))));
        jftxtAno.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jftxtAno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jftxtAnoActionPerformed(evt);
            }
        });

        jLabel2.setText("Semestre: ");

        jcbSemestre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecionar...", "1º Semestre", "2º Semestre" }));

        jLabel3.setText("Data Inicial:");

        jftxtDataInicial.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        jftxtDataInicial.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jLabel4.setText("Data Final:");

        jftxtDataFinal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        jftxtDataFinal.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jftxtDataFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jftxtDataFinalActionPerformed(evt);
            }
        });

        jbtnFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/sair.png"))); // NOI18N
        jbtnFechar.setText("Fechar");
        jbtnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnFecharActionPerformed(evt);
            }
        });

        jbtnSalvar.setText("Salvar");
        jbtnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtnFechar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jftxtAno)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jcbSemestre, 0, 276, Short.MAX_VALUE)
                    .addComponent(jftxtDataInicial)
                    .addComponent(jftxtDataFinal)
                    .addComponent(jbtnSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jftxtAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbSemestre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jftxtDataInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jftxtDataFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jbtnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jftxtAnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jftxtAnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jftxtAnoActionPerformed

    private void jbtnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnFecharActionPerformed
        dispose();
        TelaSemestresLetivos telaSemestresLetivos = new TelaSemestresLetivos();
        telaSemestresLetivos.setVisible(true);
    }//GEN-LAST:event_jbtnFecharActionPerformed

    private void jbtnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSalvarActionPerformed
        try{
            if(jftxtAno.getText().isEmpty() == true){
                JOptionPane.showMessageDialog(null, "Preencha o Campo Ano!");
                jftxtAno.requestFocus();
            }else if(Integer.parseInt(jftxtAno.getText()) < 2022){
                JOptionPane.showMessageDialog(null, "Preencha o Campo Ano Com Um Valor Valido!");
                jftxtAno.requestFocus();
            }else if(jcbSemestre.getSelectedIndex() == 0){
                JOptionPane.showMessageDialog(null, "Selecione um Semestre Valido!");
                jcbSemestre.requestFocus();
            }else if(jftxtDataInicial.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Preencha o Campo Data Inicial!");
                jftxtDataInicial.requestFocus();
            }else if(jftxtDataFinal.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Preencha o Campo Data Final!");
                jftxtDataFinal.requestFocus();
            }else if(new SimpleDateFormat("dd/MM/yyyy").parse(jftxtDataInicial.getText()).after(new SimpleDateFormat("dd/MM/yyyy").parse(jftxtDataFinal.getText())) == true){
                JOptionPane.showMessageDialog(null, "Preencha o Campo Data Final Com uma Data Valida!");
                jftxtDataFinal.requestFocus();
            }else{
                int ano = Integer.parseInt(jftxtAno.getText());
                int semestre = jcbSemestre.getSelectedIndex();
                SemestreLetivo sl = new SemestreLetivo(ano, 
                                           semestre,
                                           new SimpleDateFormat("dd/MM/yyyy").parse(jftxtDataInicial.getText()), 
                                           new SimpleDateFormat("dd/MM/yyyy").parse(jftxtDataFinal.getText()));
                if(indice == -1){
                    DisciplinaTADS.listaSL.add(sl);
                }else{
                    DisciplinaTADS.listaSL.alterar(sl, indice);
                }
                dispose();
                TelaSemestresLetivos telaSemestresLetivos = new TelaSemestresLetivos();
                telaSemestresLetivos.setVisible(true);
            }
        }catch(Exception e){
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_jbtnSalvarActionPerformed

    private void jftxtDataFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jftxtDataFinalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jftxtDataFinalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroSemestre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroSemestre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroSemestre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroSemestre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroSemestre().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton jbtnFechar;
    private javax.swing.JButton jbtnSalvar;
    private javax.swing.JComboBox<String> jcbSemestre;
    private javax.swing.JFormattedTextField jftxtAno;
    private javax.swing.JFormattedTextField jftxtDataFinal;
    private javax.swing.JFormattedTextField jftxtDataInicial;
    // End of variables declaration//GEN-END:variables
}
